cargo-features = ["edition2024"]

[workspace]
resolver = "3"
members = [
    "mefikit",
    # "mefikit-py",
    # "mefikit-ffi",
]

[profile.release]
codegen-units = 1
lto = "fat"
debug = "line-tables-only"
