cargo-features = ["edition2024"]

[workspace]
resolver = "3"
members = [
    "mefikit",
    # "mefikit-py",
    # "mefikit-ffi",
]

[profile.release]
opt-level = 3
codegen-units = 1
lto = true

[profile.flame]
inherits = "bench"
debug = true
lto = false
strip = false
