[package]
name = "mefikit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.33.2"
ndarray = { version = "0.15", features = ["serde"] }
once_cell = "1.21.3"
rayon = "1.10.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["float_roundtrip"] }
serde_yaml = "0.9.34"
todo = "0.3.0"
