[package]
name = "mefikit-py"
version = "0.1.0"
edition = "2021"

[lib]
name = "mefikit_py"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
numpy = "0.20"
mefikit = { path = "../mefikit" }
